#!/bin/zsh


echo "----- Installing Homebrew -----"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> ~/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"


echo "----- Installing Apps -----"
brew install iterm2 sublime-text google-chrome spotify


echo "----- Installing Coding Tools -----"
brew install visual-studio-code r rstudio gh docker python duckdb


echo "----- Installing Utils -----"
brew install mdcat micro tree ddgr w3m


echo "----- Installing OhMyZsh -----"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"


echo "----- Installing powerlevel10k -----"
brew install powerlevel10k
echo "source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme" >>~/.zshrc


echo "----- Installing git-open -----"
git clone https://github.com/paulirish/git-open.git $ZSH_CUSTOM/plugins/git-poen


echo "----- Authenticating With GitHub -----"
gh auth login


echo "----- Cloning configs Repo & Setting Up Files -----"
mkdir ~/Personal
cd ~/Personal
gh repo clone EricLamphere/configs
cd -
source ~/Personal/configs/setup/setup_mac.sh
